- role: robertdebock.update_package_cache
  version: 1.1.14
  tags: molecule-idempotence-notest
- role: robertdebock.core_dependencies
  version: 1.5.0
- include_role:
  name: geerlingguy.docker
  version: 2.8.1
- role: geerlingguy.pip
  version: 2.0.0
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
- role: igor_mukhin.bash_aliases
  version: v1.1.0
