---
- name: Install dependencies from apt
  ansible.builtin.package:
    name: "{{ evilginx2_packages }}"
    state: present

- name: "Ensure the {{ evilginx2_install_destination }} directory exists"
  file:
    path: "{{ evilginx2_install_destination }}"
    state: directory
    owner: root
    group: root
    mode: "0750"
