- name: "Git clone {{ evilginx_url }} and checkout to {{ evilginx_version }}"
  ansible.builtin.git:
    repo: "{{ evilginx_url }}"
    dest: "{{ evilginx_install_destination }}"
    version: "{{ evilginx_version }}"

- name: "Git clone {{ evilginx_phishlets_url }} and checkout to {{ evilginx_phishlets_version }}"
  ansible.builtin.git:
    repo: "{{ evilginx_phishlets_url }}"
    dest: "{{ evilginx_phishlets_install_destination }}"
    version: "{{ evilginx_phishlets_version }}"

- name: Build evilginx
  community.general.make:
    chdir: "{{ evilginx_install_destination }}"

- name: Run evilginx in tmux session # noqa 305
  ansible.builtin.shell: "{{ item }}"
  with_items:
    - tmux new-session -d -s "start_tmux_server"
    - tmux kill-server
    - tmux new-session -d -s "evilginx"
    - tmux send-keys -t evilginx 'cd {{ evilginx_install_destination }}' ENTER
    - tmux send-keys -t evilginx 'sudo ./build/evilginx -p {{ evilginx_phishlets_install_destination }}' ENTER
  changed_when: false