---
- name: Check if we already downloaded the zip.
  stat:
    path: "{{ evilginx2_download_destination }}"
  register: tar

- name: "Downloading evilginx-{{ evilginx2_platform }}-{{ evilginx2_arch }}.tar.gz"
  get_url:
    validate_certs: True
    url: "{{ evilginx2_url }}"
    checksum: "{{ evilginx2_sha256 }}"
    dest: "{{ evilginx2_download_destination }}"
  when: not tar.stat.exists

- name: Unzip evilginx-{{ evilginx2_platform }}-{{ evilginx2_arch }}.tar.gz
  unarchive:
    src: "{{ evilginx2_download_destination }}"
    dest: "{{ evilginx2_install_destination }}"
    remote_src: yes
    mode: 0740
  when: not tar.stat.exists

- name: Run evilginx2 in tmux session # noqa 305
  shell: "{{ item }}"
  with_items:
    - tmux new-session -d -s "start_tmux_server"
    - tmux kill-server
    - tmux new-session -d -s "evilginx2"
    - tmux send-keys -t evilginx2.0 'cd {{ evilginx2_install_destination }}/evilginx' ENTER
    - tmux send-keys -t evilginx2.0 'sudo ./evilginx' ENTER
  changed_when: false
