---
- name: Converge
  hosts: all
  tasks:
    - include_role:
        name: robertdebock.update_package_cache
      tags: molecule-idempotence-notest
    - include_role:
        name: robertdebock.bootstrap
    - include_role:
        name: robertdebock.update
      vars:
        update_reboot: no
    - include_role:
        name: robertdebock.firewall
      vars:
        firewall_services:
          - name: ssh
          - name: http
          - name: https
    - include_role:
        name: robertdebock.hostname
      vars:
        hostname: evilginx.local
        hostname_reboot: no
    - include_role:
        name: gantsign.golang
      vars:
        golang_install_dir: /opt/go
    - include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
        apply:
          environment:
            PATH: "{{ ansible_env.PATH }}:/opt/go/bin"